import { Seeder, SeederFactoryManager } from "typeorm-extension";
import { DataSource } from "typeorm";

import { ProductLine } from "../../src/entities/ProductLine";

export default class ProductLineSeeder implements Seeder {
  public async run(dataSource: DataSource, factoryManager: SeederFactoryManager): Promise<any> {
    try {
      console.log("Chạy Seeder cho bảng ProductLine");

      const repository = dataSource.getRepository(ProductLine);

      // Tạo dữ liệu mẫu
      await repository.insert([
        // {
        //   name: "Roomba",
        //   model: "iRobot Roomba i7",
        //   description: "Robot hút bụi thông minh",
        //   warranty_months: 12,
        // },
        // {
        //   name: "Roomba",
        //   model: "iRobot Roomba i7 Plus",
        //   description: "Robot hút bụi thông minh",
        //   warranty_months: 24,
        // },
        {
          name: "iPhone",
          model: "iPhone 3G 8GB",
          description: "",
          warranty_months: 12,
          os: "IOS 4.2.1",
          camera: "1.9 MP",
          cpu: "S5L8900",
          ram: "128MB",
          storage: "8GB",
          battery: "1150mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 3G 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 4.2.1",
          camera: "1.9 MP",
          cpu: "S5L8900",
          ram: "128MB",
          storage: "16GB",
          battery: "1150mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 3GS 8GB",
          description: "",
          warranty_months: 12,
          os: "IOS 6.1.6",
          camera: "3.1MP",
          cpu: "S5L8920",
          ram: "256MB",
          storage: "8GB",
          battery: "1219mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 3GS 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 6.1.6",
          camera: "3.1MP",
          cpu: "S5L8920",
          ram: "256MB",
          storage: "16GB",
          battery: "1219mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 3GS 32GB",
          description: "",
          warranty_months: 12,
          os: "IOS 6.1.6",
          camera: "3.1MP",
          cpu: "S5L8920",
          ram: "256MB",
          storage: "32GB",
          battery: "1219mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 4 8GB",
          description: "",
          warranty_months: 12,
          os: "IOS 7.1.2",
          camera: "5.0MP",
          cpu: "A4",
          ram: "512MB",
          storage: "8GB",
          battery: "1419mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 4 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 7.1.2",
          camera: "5.0MP",
          cpu: "A4",
          ram: "512MB",
          storage: "16GB",
          battery: "1419mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 4 32GB",
          description: "",
          warranty_months: 12,
          os: "IOS 7.1.2",
          camera: "5.0MP",
          cpu: "A4",
          ram: "512MB",
          storage: "32GB",
          battery: "1419mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 4S 8GB",
          description: "",
          warranty_months: 12,
          os: "IOS 9.3.6",
          camera: "8.0MP",
          cpu: "A5",
          ram: "512MB",
          storage: "8GB",
          battery: "1432mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 4S 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 9.3.6",
          camera: "8.0MP",
          cpu: "A5",
          ram: "512MB",
          storage: "16GB",
          battery: "1432mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 4S 32GB",
          description: "",
          warranty_months: 12,
          os: "IOS 9.3.6",
          camera: "8.0MP",
          cpu: "A5",
          ram: "512MB",
          storage: "32GB",
          battery: "1432mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 4S 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 9.3.6",
          camera: "8.0MP",
          cpu: "A5",
          ram: "512MB",
          storage: "64GB",
          battery: "1432mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 5 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 10.3.4",
          camera: "8.0MP",
          cpu: "A6",
          ram: "1GB",
          storage: "16GB",
          battery: "1434mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 5 32GB",
          description: "",
          warranty_months: 12,
          os: "IOS 10.3.4",
          camera: "8.0MP",
          cpu: "A6",
          ram: "1GB",
          storage: "32GB",
          battery: "1434mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 5 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 10.3.4",
          camera: "8.0MP",
          cpu: "A6",
          ram: "1GB",
          storage: "64GB",
          battery: "1434mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 5C 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 10.3.3",
          camera: "8.0MP",
          cpu: "A6",
          ram: "1GB",
          storage: "16GB",
          battery: "1508mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 5C 32GB",
          description: "",
          warranty_months: 12,
          os: "IOS 10.3.3",
          camera: "8.0MP",
          cpu: "A6",
          ram: "1GB",
          storage: "32GB",
          battery: "1508mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 5C 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 10.3.3",
          camera: "8.0MP",
          cpu: "A6",
          ram: "1GB",
          storage: "64GB",
          battery: "1508mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 5S 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 12.5.5",
          camera: "8.0MP",
          cpu: "A7",
          ram: "1GB",
          storage: "16GB",
          battery: "1508mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 5S 32GB",
          description: "",
          warranty_months: 12,
          os: "IOS 12.5.5",
          camera: "8.0MP",
          cpu: "A7",
          ram: "1GB",
          storage: "32GB",
          battery: "1508mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 5S 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 12.5.5",
          camera: "8.0MP",
          cpu: "A7",
          ram: "1GB",
          storage: "64GB",
          battery: "1508mAh",
          price: "1000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 12.5.5",
          camera: "8.0MP",
          cpu: "A8",
          ram: "1GB",
          storage: "16GB",
          battery: "1809mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 12.5.5",
          camera: "8.0MP",
          cpu: "A8",
          ram: "1GB",
          storage: "64GB",
          battery: "1809mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 12.5.5",
          camera: "8.0MP",
          cpu: "A8",
          ram: "1GB",
          storage: "128GB",
          battery: "1809mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6 Plus 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 12.5.5",
          camera: "8.0MP",
          cpu: "A8",
          ram: "1GB",
          storage: "16GB",
          battery: "2906mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6 Plus 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 12.5.5",
          camera: "8.0MP",
          cpu: "A8",
          ram: "1GB",
          storage: "64GB",
          battery: "2906mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6 Plus 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 12.5.5",
          camera: "8.0MP",
          cpu: "A8",
          ram: "1GB",
          storage: "128GB",
          battery: "2906mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6S 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A9",
          ram: "2GB",
          storage: "16GB",
          battery: "1715mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6S 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A9",
          ram: "2GB",
          storage: "64GB",
          battery: "1715mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6S 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A9",
          ram: "2GB",
          storage: "128GB",
          battery: "1715mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6S Plus 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A9",
          ram: "2GB",
          storage: "16GB",
          battery: "2750mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6S Plus 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A9",
          ram: "2GB",
          storage: "64GB",
          battery: "2750mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 6S Plus 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A9",
          ram: "2GB",
          storage: "128GB",
          battery: "2750mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone SE (1st generation) 16GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A9",
          ram: "2GB",
          storage: "16GB",
          battery: "1624mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone SE (1st generation) 32GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A9",
          ram: "2GB",
          storage: "32GB",
          battery: "1624mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone SE (1st generation) 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A9",
          ram: "2GB",
          storage: "64GB",
          battery: "1624mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone SE (1st generation) 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A9",
          ram: "2GB",
          storage: "128GB",
          battery: "1624mAh",
          price: "2000000",
        },
        {
          name: "iPhone",
          model: "iPhone 7 32GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A10",
          ram: "2GB",
          storage: "32GB",
          battery: "1960mAh",
          price: "3000000",
        },
        {
          name: "iPhone",
          model: "iPhone 7 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A10",
          ram: "2GB",
          storage: "128GB",
          battery: "1960mAh",
          price: "3000000",
        },
        {
          name: "iPhone",
          model: "iPhone 7 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A10",
          ram: "2GB",
          storage: "256GB",
          battery: "1960mAh",
          price: "3000000",
        },
        {
          name: "iPhone",
          model: "iPhone 7 Plus 32GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A10",
          ram: "3GB",
          storage: "32GB",
          battery: "2900mAh",
          price: "3000000",
        },
        {
          name: "iPhone",
          model: "iPhone 7 Plus 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A10",
          ram: "3GB",
          storage: "128GB",
          battery: "2900mAh",
          price: "3000000",
        },
        {
          name: "iPhone",
          model: "iPhone 7 Plus 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 15.7",
          camera: "12.2MP",
          cpu: "A10",
          ram: "3GB",
          storage: "256GB",
          battery: "2900mAh",
          price: "3000000",
        },
        {
          name: "iPhone",
          model: "iPhone 8 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A11",
          ram: "2GB",
          storage: "64GB",
          battery: "1821mAh",
          price: "4000000",
        },
        {
          name: "iPhone",
          model: "iPhone 8 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A11",
          ram: "2GB",
          storage: "256GB",
          battery: "1821mAh",
          price: "4000000",
        },
        {
          name: "iPhone",
          model: "iPhone 8 Plus 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A11",
          ram: "2GB",
          storage: "64GB",
          battery: "2691mAh",
          price: "5000000",
        },
        {
          name: "iPhone",
          model: "iPhone 8 Plus 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A11",
          ram: "2GB",
          storage: "256GB",
          battery: "2691mAh",
          price: "5000000",
        },
        {
          name: "iPhone",
          model: "iPhone X 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A11",
          ram: "3GB",
          storage: "64GB",
          battery: "2716mAh",
          price: "8000000",
        },
        {
          name: "iPhone",
          model: "iPhone X 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A11",
          ram: "3GB",
          storage: "256GB",
          battery: "2716mAh",
          price: "8000000",
        },
        {
          name: "iPhone",
          model: "iPhone XR 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A12 Bionic",
          ram: "3GB",
          storage: "64GB",
          battery: "2942mAh",
          price: "8000000",
        },
        {
          name: "iPhone",
          model: "iPhone XR 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A12 Bionic",
          ram: "3GB",
          storage: "128GB",
          battery: "2942mAh",
          price: "8000000",
        },
        {
          name: "iPhone",
          model: "iPhone XR 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A12 Bionic",
          ram: "3GB",
          storage: "256GB",
          battery: "2942mAh",
          price: "8000000",
        },
        {
          name: "iPhone",
          model: "iPhone XS 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A12 Bionic",
          ram: "4GB",
          storage: "64GB",
          battery: "2658mAh",
          price: "8000000",
        },
        {
          name: "iPhone",
          model: "iPhone XS 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A12 Bionic",
          ram: "4GB",
          storage: "256GB",
          battery: "2658mAh",
          price: "8000000",
        },
        {
          name: "iPhone",
          model: "iPhone XS 512GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A12 Bionic",
          ram: "4GB",
          storage: "512GB",
          battery: "2658mAh",
          price: "8000000",
        },
        {
          name: "iPhone",
          model: "iPhone XS Max 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A12 Bionic",
          ram: "4GB",
          storage: "64GB",
          battery: "3174mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone XS Max 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A12 Bionic",
          ram: "4GB",
          storage: "256GB",
          battery: "3174mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone XS Max 512GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12.2MP",
          cpu: "A12 Bionic",
          ram: "4GB",
          storage: "512GB",
          battery: "3174mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone 11 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "4GB",
          storage: "64GB",
          battery: "3110mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone 11 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "4GB",
          storage: "128GB",
          battery: "3110mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone 11 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "4GB",
          storage: "256GB",
          battery: "3110mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone 11 Pro 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "4GB",
          storage: "64GB",
          battery: "3046mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone 11 Pro 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "4GB",
          storage: "256GB",
          battery: "3046mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone 11 Pro 512GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "4GB",
          storage: "512GB",
          battery: "3046mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone 11 Pro Max 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "4GB",
          storage: "64GB",
          battery: "3969mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone 11 Pro Max 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "4GB",
          storage: "256GB",
          battery: "3969mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone 11 Pro Max 512GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "4GB",
          storage: "512GB",
          battery: "3969mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone SE (2nd generation) 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "3GB",
          storage: "64GB",
          battery: "1821mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone SE (2nd generation) 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "3GB",
          storage: "128GB",
          battery: "1821mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone SE (2nd generation) 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A13 Bionic",
          ram: "3GB",
          storage: "256GB",
          battery: "1821mAh",
          price: "10000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 mini 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "4GB",
          storage: "64GB",
          battery: "2227mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 mini 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "4GB",
          storage: "128GB",
          battery: "2227mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 mini 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "4GB",
          storage: "256GB",
          battery: "2227mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "4GB",
          storage: "64GB",
          battery: "2815mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "4GB",
          storage: "128GB",
          battery: "2815mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "4GB",
          storage: "256GB",
          battery: "2815mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 Pro 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "6GB",
          storage: "128GB",
          battery: "2815mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 Pro 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "6GB",
          storage: "256GB",
          battery: "2815mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 Pro 512GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "6GB",
          storage: "512GB",
          battery: "2815mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 Pro Max 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "6GB",
          storage: "128GB",
          battery: "3687mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 Pro Max 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "6GB",
          storage: "256GB",
          battery: "3687mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 12 Pro Max 512GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A14 Bionic",
          ram: "6GB",
          storage: "512GB",
          battery: "3687mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 mini 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "4GB",
          storage: "128GB",
          battery: "2406mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 mini 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "4GB",
          storage: "256GB",
          battery: "2406mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 mini 512GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "4GB",
          storage: "512GB",
          battery: "2406mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "4GB",
          storage: "128GB",
          battery: "3227mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "4GB",
          storage: "256GB",
          battery: "3227mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 512GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "4GB",
          storage: "512GB",
          battery: "3227mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 Pro 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "6GB",
          storage: "128GB",
          battery: "3095mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 Pro 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "6GB",
          storage: "256GB",
          battery: "3095mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 Pro 512GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "6GB",
          storage: "512GB",
          battery: "3095mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 Pro 1TB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "6GB",
          storage: "1TB",
          battery: "3095mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 Pro Max 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "6GB",
          storage: "128GB",
          battery: "4352mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 Pro Max 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "6GB",
          storage: "256GB",
          battery: "4352mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 Pro Max 512GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "6GB",
          storage: "512GB",
          battery: "4352mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone 13 Pro Max 1TB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "6GB",
          storage: "1TB",
          battery: "4352mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone SE (3rd generation) 64GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "4GB",
          storage: "64GB",
          battery: "2018mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone SE (3rd generation) 128GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "4GB",
          storage: "128GB",
          battery: "2018mAh",
          price: "12000000",
        },
        {
          name: "iPhone",
          model: "iPhone SE (3rd generation) 256GB",
          description: "",
          warranty_months: 12,
          os: "IOS 16.1.1",
          camera: "12MP",
          cpu: "A15 Bionic",
          ram: "4GB",
          storage: "256GB",
          battery: "2018mAh",
          price: "12000000",
        },
      ]);
    } catch (error) {
      console.log(error);
    }
  }
}
