export default [
  "Phường Phúc Xá, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Trúc Bạch, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Vĩnh Phúc, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Cống Vị, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Liễu Giai, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Nguyễn Trung Trực, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Quán Thánh, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Ngọc Hà, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Điện Biên, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Đội Cấn, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Ngọc Khánh, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Kim Mã, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Giảng Võ, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Thành Công, Quận Ba Đình, Thành phố Hà Nội",
  "Phường Phúc Tân, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Đồng Xuân, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Hàng Mã, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Hàng Buồm, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Hàng Đào, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Hàng Bồ, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Cửa Đông, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Lý Thái Tổ, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Hàng Bạc, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Hàng Gai, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Chương Dương Độ, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Hàng Trống, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Cửa Nam, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Hàng Bông, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Tràng Tiền, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Trần Hưng Đạo, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Phan Chu Trinh, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Hàng Bài, Quận Hoàn Kiếm, Thành phố Hà Nội",
  "Phường Phú Thượng, Quận Tây Hồ, Thành phố Hà Nội",
  "Phường Nhật Tân, Quận Tây Hồ, Thành phố Hà Nội",
  "Phường Tứ Liên, Quận Tây Hồ, Thành phố Hà Nội",
  "Phường Quảng An, Quận Tây Hồ, Thành phố Hà Nội",
  "Phường Xuân La, Quận Tây Hồ, Thành phố Hà Nội",
  "Phường Yên Phụ, Quận Tây Hồ, Thành phố Hà Nội",
  "Phường Bưởi, Quận Tây Hồ, Thành phố Hà Nội",
  "Phường Thụy Khuê, Quận Tây Hồ, Thành phố Hà Nội",
  "Phường Thượng Thanh, Quận Long Biên, Thành phố Hà Nội",
  "Phường Ngọc Thụy, Quận Long Biên, Thành phố Hà Nội",
  "Phường Giang Biên, Quận Long Biên, Thành phố Hà Nội",
  "Phường Đức Giang, Quận Long Biên, Thành phố Hà Nội",
  "Phường Việt Hưng, Quận Long Biên, Thành phố Hà Nội",
  "Phường Gia Thụy, Quận Long Biên, Thành phố Hà Nội",
  "Phường Ngọc Lâm, Quận Long Biên, Thành phố Hà Nội",
  "Phường Phúc Lợi, Quận Long Biên, Thành phố Hà Nội",
  "Phường Bồ Đề, Quận Long Biên, Thành phố Hà Nội",
  "Phường Sài Đồng, Quận Long Biên, Thành phố Hà Nội",
  "Phường Long Biên, Quận Long Biên, Thành phố Hà Nội",
  "Phường Thạch Bàn, Quận Long Biên, Thành phố Hà Nội",
  "Phường Phúc Đồng, Quận Long Biên, Thành phố Hà Nội",
  "Phường Cự Khối, Quận Long Biên, Thành phố Hà Nội",
  "Phường Nghĩa Đô, Quận Cầu Giấy, Thành phố Hà Nội",
  "Phường Nghĩa Tân, Quận Cầu Giấy, Thành phố Hà Nội",
  "Phường Mai Dịch, Quận Cầu Giấy, Thành phố Hà Nội",
  "Phường Dịch Vọng, Quận Cầu Giấy, Thành phố Hà Nội",
  "Phường Dịch Vọng Hậu, Quận Cầu Giấy, Thành phố Hà Nội",
  "Phường Quan Hoa, Quận Cầu Giấy, Thành phố Hà Nội",
  "Phường Yên Hoà, Quận Cầu Giấy, Thành phố Hà Nội",
  "Phường Trung Hoà, Quận Cầu Giấy, Thành phố Hà Nội",
  "Phường Cát Linh, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Văn Miếu, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Quốc Tử Giám, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Láng Thượng, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Ô Chợ Dừa, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Văn Chương, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Hàng Bột, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Láng Hạ, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Khâm Thiên, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Thổ Quan, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Nam Đồng, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Trung Phụng, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Quang Trung, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Trung Liệt, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Phương Liên, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Thịnh Quang, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Trung Tự, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Kim Liên, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Phương Mai, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Ngã Tư Sở, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Khương Thượng, Quận Đống Đa, Thành phố Hà Nội",
  "Phường Nguyễn Du, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Bạch Đằng, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Phạm Đình Hổ, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Bùi Thị Xuân, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Ngô Thì Nhậm, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Lê Đại Hành, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Đồng Nhân, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Phố Huế, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Đống Mác, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Thanh Lương, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Thanh Nhàn, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Cầu Dền, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Bách Khoa, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Đồng Tâm, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Vĩnh Tuy, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Bạch Mai, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Quỳnh Mai, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Quỳnh Lôi, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Minh Khai, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Trương Định, Quận Hai Bà Trưng, Thành phố Hà Nội",
  "Phường Thanh Trì, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Vĩnh Hưng, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Định Công, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Mai Động, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Tương Mai, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Đại Kim, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Tân Mai, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Hoàng Văn Thụ, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Giáp Bát, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Lĩnh Nam, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Thịnh Liệt, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Trần Phú, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Hoàng Liệt, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Yên Sở, Quận Hoàng Mai, Thành phố Hà Nội",
  "Phường Nhân Chính, Quận Thanh Xuân, Thành phố Hà Nội",
  "Phường Thượng Đình, Quận Thanh Xuân, Thành phố Hà Nội",
  "Phường Khương Trung, Quận Thanh Xuân, Thành phố Hà Nội",
  "Phường Khương Mai, Quận Thanh Xuân, Thành phố Hà Nội",
  "Phường Thanh Xuân Trung, Quận Thanh Xuân, Thành phố Hà Nội",
  "Phường Phương Liệt, Quận Thanh Xuân, Thành phố Hà Nội",
  "Phường Hạ Đình, Quận Thanh Xuân, Thành phố Hà Nội",
  "Phường Khương Đình, Quận Thanh Xuân, Thành phố Hà Nội",
  "Phường Thanh Xuân Bắc, Quận Thanh Xuân, Thành phố Hà Nội",
  "Phường Thanh Xuân Nam, Quận Thanh Xuân, Thành phố Hà Nội",
  "Phường Kim Giang, Quận Thanh Xuân, Thành phố Hà Nội",
  "Thị trấn Sóc Sơn, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Bắc Sơn, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Minh Trí, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Hồng Kỳ, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Nam Sơn, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Trung Giã, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Tân Hưng, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Minh Phú, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Phù Linh, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Bắc Phú, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Tân Minh, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Quang Tiến, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Hiền Ninh, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Tân Dân, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Tiên Dược, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Việt Long, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Xuân Giang, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Mai Đình, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Đức Hoà, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Thanh Xuân, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Đông Xuân, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Kim Lũ, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Phú Cường, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Phú Minh, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Phù Lỗ, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Xã Xuân Thu, Huyện Sóc Sơn, Thành phố Hà Nội",
  "Thị trấn Đông Anh, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Xuân Nộn, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Thuỵ Lâm, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Bắc Hồng, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Nguyên Khê, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Nam Hồng, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Tiên Dương, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Vân Hà, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Uy Nỗ, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Vân Nội, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Liên Hà, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Việt Hùng, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Kim Nỗ, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Kim Chung, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Dục Tú, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Đại Mạch, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Vĩnh Ngọc, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Cổ Loa, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Hải Bối, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Xuân Canh, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Võng La, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Tầm Xá, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Mai Lâm, Huyện Đông Anh, Thành phố Hà Nội",
  "Xã Đông Hội, Huyện Đông Anh, Thành phố Hà Nội",
  "Thị trấn Yên Viên, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Yên Thường, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Yên Viên, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Ninh Hiệp, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Đình Xuyên, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Dương Hà, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Phù Đổng, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Trung Mầu, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Lệ Chi, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Cổ Bi, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Đặng Xá, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Phú Thị, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Kim Sơn, Huyện Gia Lâm, Thành phố Hà Nội",
  "Thị trấn Trâu Quỳ, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Dương Quang, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Dương Xá, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Đông Dư, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Đa Tốn, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Kiêu Kỵ, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Bát Tràng, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Kim Lan, Huyện Gia Lâm, Thành phố Hà Nội",
  "Xã Văn Đức, Huyện Gia Lâm, Thành phố Hà Nội",
  "Phường Cầu Diễn, Quận Nam Từ Liêm, Thành phố Hà Nội",
  "Phường Xuân Phương, Quận Nam Từ Liêm, Thành phố Hà Nội",
  "Phường Phương Canh, Quận Nam Từ Liêm, Thành phố Hà Nội",
  "Phường Mỹ Đình 1, Quận Nam Từ Liêm, Thành phố Hà Nội",
  "Phường Mỹ Đình 2, Quận Nam Từ Liêm, Thành phố Hà Nội",
  "Phường Tây Mỗ, Quận Nam Từ Liêm, Thành phố Hà Nội",
  "Phường Mễ Trì, Quận Nam Từ Liêm, Thành phố Hà Nội",
  "Phường Phú Đô, Quận Nam Từ Liêm, Thành phố Hà Nội",
  "Phường Đại Mỗ, Quận Nam Từ Liêm, Thành phố Hà Nội",
  "Phường Trung Văn, Quận Nam Từ Liêm, Thành phố Hà Nội",
  "Thị trấn Văn Điển, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Tân Triều, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Thanh Liệt, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Tả Thanh Oai, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Hữu Hoà, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Tam Hiệp, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Tứ Hiệp, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Yên Mỹ, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Vĩnh Quỳnh, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Ngũ Hiệp, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Duyên Hà, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Ngọc Hồi, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Vạn Phúc, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Đại áng, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Liên Ninh, Huyện Thanh Trì, Thành phố Hà Nội",
  "Xã Đông Mỹ, Huyện Thanh Trì, Thành phố Hà Nội",
  "Phường Thượng Cát, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Liên Mạc, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Đông Ngạc, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Đức Thắng, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Thụy Phương, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Tây Tựu, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Xuân Đỉnh, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Xuân Tảo, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Minh Khai, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Cổ Nhuế 1, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Cổ Nhuế 2, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Phú Diễn, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Phường Phúc Diễn, Quận Bắc Từ Liêm, Thành phố Hà Nội",
  "Thị trấn Chi Đông, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Đại Thịnh, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Kim Hoa, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Thạch Đà, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Tiến Thắng, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Tự Lập, Huyện Mê Linh, Thành phố Hà Nội",
  "Thị trấn Quang Minh, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Thanh Lâm, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Tam Đồng, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Liên Mạc, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Vạn Yên, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Chu Phan, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Tiến Thịnh, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Mê Linh, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Văn Khê, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Hoàng Kim, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Tiền Phong, Huyện Mê Linh, Thành phố Hà Nội",
  "Xã Tráng Việt, Huyện Mê Linh, Thành phố Hà Nội",
  "Phường Nguyễn Trãi, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Mộ Lao, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Văn Quán, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Vạn Phúc, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Yết Kiêu, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Quang Trung, Quận Hà Đông, Thành phố Hà Nội",
  "Phường La Khê, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Phú La, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Phúc La, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Hà Cầu, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Yên Nghĩa, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Kiến Hưng, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Phú Lãm, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Phú Lương, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Dương Nội, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Đồng Mai, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Biên Giang, Quận Hà Đông, Thành phố Hà Nội",
  "Phường Lê Lợi, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Phường Phú Thịnh, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Phường Ngô Quyền, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Phường Quang Trung, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Phường Sơn Lộc, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Phường Xuân Khanh, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Xã Đường Lâm, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Phường Viên Sơn, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Xã Xuân Sơn, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Phường Trung Hưng, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Xã Thanh Mỹ, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Phường Trung Sơn Trầm, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Xã Kim Sơn, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Xã Sơn Đông, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Xã Cổ Đông, Thị xã Sơn Tây, Thành phố Hà Nội",
  "Thị trấn Tây Đằng, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Phú Cường, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Cổ Đô, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Tản Hồng, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Vạn Thắng, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Châu Sơn, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Phong Vân, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Phú Đông, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Phú Phương, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Phú Châu, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Thái Hòa, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Đồng Thái, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Phú Sơn, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Minh Châu, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Vật Lại, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Chu Minh, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Tòng Bạt, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Cẩm Lĩnh, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Sơn Đà, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Đông Quang, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Tiên Phong, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Thụy An, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Cam Thượng, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Thuần Mỹ, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Tản Lĩnh, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Ba Trại, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Minh Quang, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Ba Vì, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Vân Hòa, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Yên Bài, Huyện Ba Vì, Thành phố Hà Nội",
  "Xã Khánh Thượng, Huyện Ba Vì, Thành phố Hà Nội",
  "Thị trấn Phúc Thọ, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Vân Hà, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Vân Phúc, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Vân Nam, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Xuân Phú, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Phương Độ, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Sen Chiểu, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Cẩm Đình, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Võng Xuyên, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Thọ Lộc, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Long Xuyên, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Thượng Cốc, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Hát Môn, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Tích Giang, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Thanh Đa, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Trạch Mỹ Lộc, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Phúc Hòa, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Ngọc Tảo, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Phụng Thượng, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Tam Thuấn, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Tam Hiệp, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Hiệp Thuận, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Xã Liên Hiệp, Huyện Phúc Thọ, Thành phố Hà Nội",
  "Thị trấn Phùng, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Trung Châu, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Thọ An, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Thọ Xuân, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Hồng Hà, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Liên Hồng, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Liên Hà, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Hạ Mỗ, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Liên Trung, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Phương Đình, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Thượng Mỗ, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Tân Hội, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Tân Lập, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Đan Phượng, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Đồng Tháp, Huyện Đan Phượng, Thành phố Hà Nội",
  "Xã Song Phượng, Huyện Đan Phượng, Thành phố Hà Nội",
  "Thị trấn Trạm Trôi, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Đức Thượng, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Minh Khai, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Dương Liễu, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Di Trạch, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Đức Giang, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Cát Quế, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Kim Chung, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Yên Sở, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Sơn Đồng, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Vân Canh, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Đắc Sở, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Lại Yên, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Tiền Yên, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Song Phương, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã An Khánh, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã An Thượng, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Vân Côn, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã La Phù, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Đông La, Huyện Hoài Đức, Thành phố Hà Nội",
  "Xã Đông Xuân, Huyện Quốc Oai, Thành phố Hà Nội",
  "Thị trấn Quốc Oai, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Sài Sơn, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Phượng Cách, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Yên Sơn, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Ngọc Liệp, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Ngọc Mỹ, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Liệp Tuyết, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Thạch Thán, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Đồng Quang, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Phú Cát, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Tuyết Nghĩa, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Nghĩa Hương, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Cộng Hòa, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Tân Phú, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Đại Thành, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Phú Mãn, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Cấn Hữu, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Tân Hòa, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Hòa Thạch, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Đông Yên, Huyện Quốc Oai, Thành phố Hà Nội",
  "Xã Yên Trung, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Yên Bình, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Tiến Xuân, Huyện Thạch Thất, Thành phố Hà Nội",
  "Thị trấn Liên Quan, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Đại Đồng, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Cẩm Yên, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Lại Thượng, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Phú Kim, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Hương Ngải, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Canh Nậu, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Kim Quan, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Dị Nậu, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Bình Yên, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Chàng Sơn, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Thạch Hoà, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Cần Kiệm, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Hữu Bằng, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Phùng Xá, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Tân Xã, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Thạch Xá, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Bình Phú, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Hạ Bằng, Huyện Thạch Thất, Thành phố Hà Nội",
  "Xã Đồng Trúc, Huyện Thạch Thất, Thành phố Hà Nội",
  "Thị trấn Chúc Sơn, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Thị trấn Xuân Mai, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Phụng Châu, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Tiên Phương, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Đông Sơn, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Đông Phương Yên, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Phú Nghĩa, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Trường Yên, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Ngọc Hòa, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Thủy Xuân Tiên, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Thanh Bình, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Trung Hòa, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Đại Yên, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Thụy Hương, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Tốt Động, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Lam Điền, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Tân Tiến, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Nam Phương Tiến, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Hợp Đồng, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Hoàng Văn Thụ, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Hoàng Diệu, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Hữu Văn, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Quảng Bị, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Mỹ Lương, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Thượng Vực, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Hồng Phong, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Đồng Phú, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Trần Phú, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Văn Võ, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Đồng Lạc, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Hòa Chính, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Xã Phú Nam An, Huyện Chương Mỹ, Thành phố Hà Nội",
  "Thị trấn Kim Bài, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Cự Khê, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Bích Hòa, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Mỹ Hưng, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Cao Viên, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Bình Minh, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Tam Hưng, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Thanh Cao, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Thanh Thùy, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Thanh Mai, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Thanh Văn, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Đỗ Động, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Kim An, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Kim Thư, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Phương Trung, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Tân Ước, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Dân Hòa, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Liên Châu, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Cao Dương, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Xuân Dương, Huyện Thanh Oai, Thành phố Hà Nội",
  "Xã Hồng Dương, Huyện Thanh Oai, Thành phố Hà Nội",
  "Thị trấn Thường Tín, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Ninh Sở, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Nhị Khê, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Duyên Thái, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Khánh Hà, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Hòa Bình, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Văn Bình, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Hiền Giang, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Hồng Vân, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Vân Tảo, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Liên Phương, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Văn Phú, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Tự Nhiên, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Tiền Phong, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Hà Hồi, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Thư Phú, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Nguyễn Trãi, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Quất Động, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Chương Dương, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Tân Minh, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Lê Lợi, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Thắng Lợi, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Dũng Tiến, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Thống Nhất, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Nghiêm Xuyên, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Tô Hiệu, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Văn Tự, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Vạn Điểm, Huyện Thường Tín, Thành phố Hà Nội",
  "Xã Minh Cường, Huyện Thường Tín, Thành phố Hà Nội",
  "Thị trấn Phú Minh, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Thị trấn Phú Xuyên, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Hồng Minh, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Phượng Dực, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Văn Nhân, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Thụy Phú, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Tri Trung, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Đại Thắng, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Phú Túc, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Văn Hoàng, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Hồng Thái, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Hoàng Long, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Quang Trung, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Nam Phong, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Nam Triều, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Tân Dân, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Sơn Hà, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Chuyên Mỹ, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Khai Thái, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Phúc Tiến, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Vân Từ, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Tri Thủy, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Đại Xuyên, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Phú Yên, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Bạch Hạ, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Quang Lãng, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Châu Can, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Xã Minh Tân, Huyện Phú Xuyên, Thành phố Hà Nội",
  "Thị trấn Vân Đình, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Viên An, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Viên Nội, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Hoa Sơn, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Quảng Phú Cầu, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Trường Thịnh, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Cao Thành, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Liên Bạt, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Sơn Công, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Đồng Tiến, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Phương Tú, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Trung Tú, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Đồng Tân, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Tảo Dương Văn, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Vạn Thái, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Minh Đức, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Hòa Lâm, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Hòa Xá, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Trầm Lộng, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Kim Đường, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Hòa Nam, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Hòa Phú, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Đội Bình, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Đại Hùng, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Đông Lỗ, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Phù Lưu, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Đại Cường, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Lưu Hoàng, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Xã Hồng Quang, Huyện Ứng Hòa, Thành phố Hà Nội",
  "Thị trấn Đại Nghĩa, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Đồng Tâm, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Thượng Lâm, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Tuy Lai, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Phúc Lâm, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Mỹ Thành, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Bột Xuyên, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã An Mỹ, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Hồng Sơn, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Lê Thanh, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Xuy Xá, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Phùng Xá, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Phù Lưu Tế, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Đại Hưng, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Vạn Kim, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Đốc Tín, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Hương Sơn, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Hùng Tiến, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã An Tiến, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Hợp Tiến, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã Hợp Thanh, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Xã An Phú, Huyện Mỹ Đức, Thành phố Hà Nội",
  "Phường Duyên Hải, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Lào Cai, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Phố Mới, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Cốc Lếu, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Kim Tân, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Bắc Lệnh, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Pom Hán, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Xuân Tăng, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Bình Minh, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Thống Nhất, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Xã Đồng Tuyển, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Xã Vạn Hoà, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Bắc Cường, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Phường Nam Cường, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Xã Cam Đường, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Xã Tả Phời, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Xã Hợp Thành, Thành phố Lào Cai, Tỉnh Lào Cai",
  "Thị trấn Bát Xát, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã A Mú Sung, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Nậm Chạc, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã A Lù, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Trịnh Tường, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Ngải Thầu, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Y Tý, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Cốc Mỳ, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Dền Sáng, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Bản Vược, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Sàng Ma Sáo, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Bản Qua, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Mường Vi, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Dền Thàng, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Bản Xèo, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Mường Hum, Huyện Bát Xát, Tỉnh Lào Cai",
  "Xã Trung Lèng Hồ, Huyện Bát Xát, Tỉnh Lào Cai",
];
